### ISSUE TITLE
Play Style ID Ref

### ISSUE THREAD

**Issue by stephdotnet** [lorenzh/fut-api#13]
Hello,

Sorry to bother you, but any idea where to find the "player style ID" reference? I've notice that there are the following values :

250 seems to be BASIC

But i've also seen "265", "261" so if one of you have the complete list of reference it will be usefull!

Thanks in advance =)

**Comment by JKetelaar** [comment]
Though it's the C# language, it should be enough to answer your question: https://github.com/trydis/FIFA-Ultimate-Team-Toolkit/blob/6284a59b7e7881153235b1ef4fc2f35fd7ce668e/UltimateTeam.Toolkit/Parameters/ChemistryStyle.cs

**Comment by stephdotnet** [comment]
It's perfect, you are the boss!
