### ISSUE TITLE
Log in API: data information

### ISSUE THREAD

**Issue by CiccioK** [lorenzh/fut-api#33]
Hi all,
I am trying to use the login API, but something goes wrong!  :'( 

Follow the code lines:
  var futapi = require("fut-api");

  var apiClient = new futapi();

  function twoFactorCodeCb(next){
      /* send your authentication code with the "next" method */
      next("numeric code (6 digits) that I receive when I make changes to my profile account");
	}
    apiClient.login("xxxx@gmail.com","xxxpwdxxx","SECRET ANSWER to the secret question", "xone",
    	twoFactorCodeCb,
    	function(error,response){
    	if(error) {
        	return console.log(error);
        }
    	console.log("logged in.");
        
        apiClient.getCredits(function(error, response){ });
        
    });  

Received error: "Error: Unknow response. Unable to login."

Please help me!
Thanks

**Comment by buddy274** [comment]
Does anyone have a solution on this??? Other API's seem to work and they have fixed this login issue....

**Comment by pieczorx** [comment]
@buddy274 Check out this: https://github.com/lorenzh/fut-api/pull/27

**Comment by buddy274** [comment]
@pieczorx: Htx, for your answer. This was an old problem, that I also fixed in January. But the login doesn't work anymore, which is another issue since EA probably revised their login process again.

**Comment by elderbernini** [comment]
Hi, could someone tell me if the login is working?

**Comment by CiccioK** [comment]
the Login seems to work
