### ISSUE TITLE
Rewrite in es7?

### ISSUE THREAD

**Issue by gregbarcza** [lorenzh/fut-api#5]
Hi @lorenzh ! 
You did great job with this repo. I would like to contribute to it however i would prefer to rewrite it in ES7. What do you think?

**Comment by lorenzh** [comment]
Hey @barczaG,

i have planned to rewrite it in typescript, but i don't have time at the moment.
i am a .net developer and quite new in js and i think it's easier for me to write and understand it in ts.

**Comment by gregbarcza** [comment]
Please note that typescript and ES7 are not mutually exclusive, since typescript is based on the ecmascript specification so you have to learn it anyhow :) However I don't really like typescript for several reasons but I plan to use this insted: http://flowtype.org/. Anyway I will start the refactor this week, can I use your code as a base?

**Comment by lorenzh** [comment]
ok i see. sounds good.
i have started to learn js with this project but it was really exhausting to find errors but i think that flowtype could help me a lot.
well then lets do this in es7.

**Comment by blerest** [comment]
@barczaG @lorenzh do you have some news regarding ES7?

**Comment by lorenzh** [comment]
The project moved to https://github.com/futjs/fut-api 

I don't have enough time right now but @barczaG  did some changes
