### ISSUE TITLE
throw error on action with expired item

### ISSUE THREAD

**Issue by bauer01** [lorenzh/fut-api#6]
Hi,
this library look awesome, but I'm still facing problem when adding some item to watchlist while it expired...is there some option to detect successfull add from server response?

**Comment by lorenzh** [comment]
you can pass a second parameter to the response of the  "addToWatchlist" 

```
apiClient.addToWatchlist(response.auctionInfo[0].tradeId, function(error, response){
/* response : { debug: '', string: '', code: '409', reason: '' } */
      if(response.code == "409") {
            console.log('unable to add item to watchlist');
      }
});
```
