### ISSUE TITLE
How you made eaHasher.js ?

### ISSUE THREAD

**Issue by gregbarcza** [lorenzh/fut-api#8]
Hi,

Since Fifa 17 is coming and things may change can you please explain how you made the eahasher.js file as I might need to change some code there. 

Thanks!

**Comment by lorenzh** [comment]
eaHasher.js is still working for fifa 17. 

it's the [MD5](https://en.wikipedia.org/wiki/MD5) algorithm

**Comment by stephdotnet** [comment]
Yes the library (fut-api) works for fifa 17, I just changed "16" by "17" in the urls present in "lib/urls.js" and replaced "FFA16PCC" by "FFA17PCC" in login.js 

By the way, thanks to the author for this amazing job. <3
